model_list:
  # Qwen2.5 Vision-Language 72B (Free)
  - model_name: qwen2.5-vl-72b-instruct:free
    litellm_params:
      model: openrouter/qwen/qwen2.5-vl-72b-instruct
      apikey: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1
